---
version: "3"

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.0.0/16

services:

  appdaemon:
    build:
      context: ./appdaemon/docker
      args:
        VERSION: 3.0.2
    container_name: appdaemon
    depends_on:
      - hass
    environment:
      EXTRA_CMD: -D INFO
    image: bachya/appdaemon
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - appdaemon-config:/conf
      - shared:/shared

  amazon-dash:
    command: amazon-dash run --config /config/amazon-dash.yml
    container_name: amazon-dash
    depends_on:
      - hass
    image: nekmo/amazon-dash:latest
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - amazon-dash-config:/config:ro

  glances:
    build:
      context: ./glances/docker
      args:
        version: 3.0
    command: /usr/bin/supervisord -c /etc/supervisor.conf
    container_name: glances
    image: bachya/glances
    ports:
      - "61208:61208/tcp"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - glances-config:/etc/glances:ro

  hass:
    container_name: hass
    depends_on:
      - glances
      - mosquitto
      - mysql
    devices:
      - "/dev/zwave:/dev/zwave"
    image: homeassistant/home-assistant:0.89.2
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - hass-config:/config
      - shared:/shared

  jupyterlab:
    build:
      context: ./jupyterlab/docker
    container_name: jupyterlab
    depends_on:
      - hass
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    image: bachya/jupyterlab
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - jupyterlab-config:/home/jovyan

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.5.8
    ports:
      - "1883:1883/tcp"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl:/etc/ssl:ro
      - /usr/share/ca-certificates:/usr/share/ca-certificates:ro
      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  mysql:
    container_name: mysql
    environment:
      MYSQL_DATABASE: recorder_db
      MYSQL_PASSWORD: recorder_password
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_USER: recorder_user
    image: bianjp/mariadb-alpine:latest
    ports:
      - "3306:3306/tcp"
    restart: unless-stopped
    volumes:
      - /var/lib/docker/mysql:/var/lib/mysql

  nginx:
    build:
      context: ./nginx/docker
      args:
        libmaxminddb_version: 1.3.2
        nginx_version: 1.15.9
        ngx_http_geoip2_module_version: 3.2
    cap_add:
      - NET_ADMIN
    command: /usr/bin/supervisord -c /etc/supervisor.conf
    container_name: nginx
    depends_on:
      - appdaemon
      - hass
    image: bachya/nginx
    networks:
      default:
        ipv4_address: 192.168.7.7
    ports:
      - "443:443/tcp"
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl:/etc/ssl:ro
      - fail2ban-config:/etc/fail2ban
      - nginx-config:/etc/nginx

  portainer:
    container_name: portainer
    image: portainer/portainer:1.20.2
    ports:
      - "9000:9000/tcp"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-config:/data

  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin:v1.6.0
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - tasmoadmin-config:/data

volumes:

  amazon-dash-config:
  appdaemon-config:
  fail2ban-config:
  glances-config:
  hass-config:
  jupyterlab-config:
  mosquitto-config:
  mosquitto-data:
  nginx-config:
  portainer-config:
  shared:
  tasmoadmin-config:
