---
binary_sensor:
  - platform: bayesian
    name: Aaron Home
    probability_threshold: 0.95
    prior: .625
    observations:
      - entity_id: device_tracker.2010_subaru_legacy
        prob_given_true: 0.75
        platform: state
        to_state: home
      - entity_id: device_tracker.aaron_bachs_iphone
        prob_given_true: 0.90
        platform: state
        to_state: home
      - entity_id: device_tracker.aaron_iphone
        prob_given_true: 0.85
        platform: state
        to_state: home

  - platform: bayesian
    name: Britt Home
    probability_threshold: 0.95
    prior: .75
    observations:
      - entity_id: device_tracker.britt_iphone
        prob_given_true: 0.90
        platform: state
        to_state: home

device_tracker:
  - platform: automatic
    client_id: !secret automatic_client_id
    secret: !secret automatic_secret
    current_location: true

  - platform: owntracks
    max_gps_accuracy: 200
    mqtt_topic: !secret mqtt_topic_owntracks

  - platform: tile
    username: !secret tile_username
    password: !secret tile_password
    monitored_variables:
      - TILE
