---
automation:
  - alias: Turn on backyard lights at top double tap of kitchen patio light
    trigger:
      platform: event
      event_type: zwave.node_event
      event_data:
        entity_id: zwave.kitchen_patio_light
        basic_level: 255
    action:
      service: switch.turn_on
      data:
        entity_id: switch.backyard_lights
  - alias: Turn off backyard lights at bottom double tap of kitchen patio light
    trigger:
      platform: event
      event_type: zwave.node_event
      event_data:
        entity_id: zwave.kitchen_patio_light
        basic_level: 0
    action:
      service: switch.turn_off
      data:
        entity_id: switch.backyard_lights

openuv:
  api_key: !secret openuv_api_key
  sensors:
    monitored_conditions:
      - current_ozone_level
      - current_uv_index
      - current_uv_level
      - max_uv_index
      - safe_exposure_time_type_1
      - safe_exposure_time_type_3

sensor:
  - platform: airvisual
    api_key: !secret airvisual_api_key
    monitored_conditions:
      - us
    show_on_map: false
  - platform: darksky
    api_key: !secret dark_sky_api_key
    monitored_conditions:
      - cloud_cover
      - humidity
      - precip_probability
      - precip_type
      - pressure
      - temperature
      - wind_speed
  - platform: pollen
    zip_code: !secret pollen_zip_code
    monitored_conditions:
      - allergy_average_forecasted
      - allergy_average_historical
      - allergy_index_today
      - allergy_index_tomorrow
      - allergy_index_yesterday
      - disease_average_forecasted
  - platform: season

sun:
