---
group:
  outdoor_lights:
    entities:
      - switch.backyard_lights
      - switch.front_patio_light
      - switch.kitchen_patio_light

  patio_lights:
    entities:
      - switch.front_patio_light
      - switch.kitchen_patio_light

sensor:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    monitored_conditions:
      - cloud_cover
      - humidity
      - precip_probability
      - precip_type
      - pressure
      - temperature
      - wind_speed

  - platform: season

sun:
