---
sensor:
  - platform: airvisual
    api_key: !secret airvisual_api_key
    monitored_conditions:
      - us
    show_on_map: false
  - platform: darksky
    api_key: !secret dark_sky_api_key
    monitored_conditions:
      - cloud_cover
      - humidity
      - precip_probability
      - precip_type
      - pressure
      - temperature
      - wind_speed
  - platform: pollen
    zip_code: !secret pollen_zip_code
    monitored_conditions:
      - allergy_average_forecasted
      - allergy_average_historical
      - allergy_index_today
      - allergy_index_tomorrow
      - allergy_index_yesterday
      - disease_average_forecasted
  - platform: season

sun:
