---
sensor:
  - platform: template
    sensors:
      secure_status:
        friendly_name: Security Status
        value_template: >
          {% if is_state('lock.front_door', 'locked')
             and is_state('lock.garage_fire_door', 'locked')
             and not is_state('alarm_control_panel.simplisafe', 'disarmed')
             and is_state('cover.garage_door', 'closed') %}
            Secure
          {% else %}
            Open
          {% endif %}
        icon_template: >
          {% if is_state('lock.front_door', 'locked')
             and is_state('lock.garage_fire_door', 'locked')
             and not is_state('alarm_control_panel.simplisafe', 'disarmed')
             and is_state('cover.garage_door', 'closed') %}
            mdi:lock
          {% else %}
            mdi:lock-open-outline
          {% endif %}

simplisafe:
  accounts:
    - username: !secret simplisafe_username
      password: !secret simplisafe_password
