---
sensor:
  # Available Versions
  - platform: command_line
    name: AppDaemon Available
    command: >-
      curl -L
      -H "User-Agent: Home Assistant"
      -H "Content-Type: application/json"
      https://pypi.python.org/pypi/appdaemon/json
    value_template: '{{ value_json.info.version }}'
    scan_interval: 600

  - platform: command_line
    name: Mosquitto Available
    command: >-
      curl -L
      -H "User-Agent: Home Assistant"
      -H "Content-Type: application/json"
      https://api.github.com/repos/eclipse/mosquitto/tags
    value_template: '{{ value_json[0].name[1:] }}'
    scan_interval: 600

  - platform: command_line
    name: Portainer Available
    command: >-
      curl -L
      -H "User-Agent: Home Assistant"
      -H "Content-Type: application/json"
      https://api.github.com/repos/portainer/portainer/releases/latest
    value_template: '{{ value_json.tag_name }}'
    scan_interval: 600

  - platform: command_line
    name: TasmoAdmin Available
    command: >-
      curl -L
      -H "User-Agent: Home Assistant"
      -H "Content-Type: application/json"
      https://api.github.com/repos/reloxx13/TasmoAdmin/releases/latest
    value_template: '{{ value_json.tag_name[1:] }}'
    scan_interval: 600

  - platform: command_line
    name: Tasmota Available
    command: >-
      curl -L
      -H "User-Agent: Home Assistant"
      -H "Content-Type: application/json"
      https://api.github.com/repos/arendst/Sonoff-Tasmota/releases/latest
    value_template: '{{ value_json.tag_name[1:] }}'
    scan_interval: 600

  - platform: command_line
    name: Xiaomi Hack Available
    command: >-
      curl -L
      -H "User-Agent: Home Assistant"
      -H "Content-Type: application/json"
      https://api.github.com/repos/EliasKotlyar/Xiaomi-Dafang-Hacks/commits |
      python3 -c "import sys, json; "
        "print(json.load(sys.stdin)[0]['commit']['author']['date'])" |
        /usr/bin/md5sum | /usr/bin/cut -f1 -d" " | fold -w 8 | head -n 1
    scan_interval: 600

  - platform: command_line
    name: Yi Hack Available
    command: >-
      curl -L
      -H "User-Agent: Home Assistant"
      -H "Content-Type: application/json"
      https://api.github.com/repos/shadow-1/yi-hack-v3/releases/latest
    value_template: '{{ value_json.tag_name }}'
    scan_interval: 600

  - platform: version
    name: HASS Available
    source: docker
    beta: true

  # Installed Versions
  - platform: command_line
    name: Xiaomi Hack Installed
    command: >-
      ssh -i /config/id_rsa -o StrictHostKeyChecking=no
      root@garage-camera.phil.iot
      cat /system/sdcard/.lastCommitDate |
        /usr/bin/md5sum | /usr/bin/cut -f1 -d" " | fold -w 8 | head -n 1

  - platform: command_line
    name: Yi Hack Installed
    command: >
      ssh -i /config/id_rsa -o StrictHostKeyChecking=no
      root@kitchen-camera.phil.lan
      cat /home/yi-hack-v3/.hackinfo | grep VERSION | awk -F= \'{ print $2 }\'

  - platform: version
    name: HASS Installed

    # Networking
  - platform: cert_expiry
    name: SSL Expiry
    host: !secret ssl_cert_host

  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload
