---
automation:
  - alias: "Slack slash command"
    trigger:
      platform: webhook
      webhook_id: 12345678-9012-abcd-ef12-4567890abcde
    action:
      - event: SLACK_SLASH_COMMAND
        event_data_template:
          command: "{{ trigger.data.command }}"
          text: "{{ trigger.data.text }}"
          response_url: "{{ trigger.data.response_url }}"
